### ISSUE TITLE
upload progress bar when uploading from front end

### ISSUE THREAD

**Issue by blackb2b** [gdarko/wp-vimeo-videos#10]
I purchased the Premium version. How can I have upload progress bar when uploading from front end?

Best regards,

**Comment by gdarko** [comment]
Hello,

The is planned feature, it's not yet ready. Hopefully we will finish it in next versions.

Best,
Darko

**Comment by blackb2b** [comment]
Thanks. wish you can improve the front end upload much further.

Best regards,

**Comment by gdarko** [comment]
Hi @blackb2b,

In version 1.6.0 we implemented progress bar for the front-end feel free to check it. Also we added support for WPForms, another forms plugin.

Best Regards,
Darko
