### ISSUE TITLE
Getting the vimeo Id from the gravity form field value

### ISSUE THREAD

**Issue by directingchange** [gdarko/wp-vimeo-videos#11]
Hi, how do I retrieve the vimeo id from the gravity form entry.  For example in other fields I would use 

$fieldValue = rgar($entryArray, 1) where 1 is the field id. 

This works for most fields but does not return a value for the vimeo upload field. When I export the entry I see the json that was returned for the film upload and the vimeo Id is in there. I just can't figure out the syntax to get it.

{"url":null,"path":null,"title":"1 video","description":"My Video","vimeo":"999999999","error":""}

**Comment by gdarko** [comment]
Hey,

You need to decode the JSON value, something like this:

```php
$fieldValue = rgar($entryArray, 1) 
$decoded  = json_decode($fieldValue);
if(isset($decoded['vimeo'])) {
   $vimeo_id = $decoded['vimeo'];
   // Then you can print the url, etc. eg:
   echo 'https://vimeo.com/'.$vimeo_id;
}
```

Let me know if that works.

Best,
Darko

**Comment by directingchange** [comment]
Unfortunately that didn't work.  This seems to be an issue with 

$entry = GFAPI::get_entry( $entry_id );

A var_dump of $entry shows an empty string in the Vimeo Upload field.  Exporting the same entry to CSV shows the JSON in the vimeo upload field. I'm not sure why they are different.

**Comment by gdarko** [comment]
Are you calling this in a hook? Can you post the whole code? It may be too early to use that code because the Video is saved a bit later and different hook is available.

**Comment by directingchange** [comment]
I am using this in a hook when a form is loaded to judge a film, I read the original entry form fields to get the information for the judging form.  Currently all fields work fine except the $entryVimeoUpl variable is always empty.  This should have the json returned from the vimeo upload. When I use the gravity forms export menu option, which exports to csv, the json is there.

add_filter( 'gform_pre_render', 'addDescription' );
function addDescription( $form ) {
	foreach( $form['fields'] as &$field ) {
      if ( $field->label == 'entryDescription' ) {
        $entry_id = $_GET['entryId']; //id is passed as URL parameter
        $entry = GFAPI::get_entry( $entry_id );  //get the form entry object
        if($entry) {
            $entryDesc = rgar( $entry, '5' );
            $entryURL = rgar( $entry, '9' );
            $entryTitle = rgar( $entry, '1' );
            $entryExt = substr($entryURL,strLen($entryURL)-3,3); //file extension for non-videos
            $entryVimeoId = rgar( $entry, '115' ); //manual entry of the vimeo id as a work around
            $entryVimeoUpl = rgar( $entry, '114'); //the vimeo upload field
        if (strlen($entryVimeoId) == 9) {
            $field->content = '<h2>Title</h2><p>'.$entryTitle.'</p>
            <h2>Description from the submitter</h2><p>'.$entryDesc.'</p><iframe allowFullScreen frameborder="0" height="500" mozallowfullscreen src="https://player.vimeo.com/video/'.$entryVimeoId.'"	webkitAllowFullScreen width="800"></iframe>';
        }
}

**Comment by directingchange** [comment]
As an alternative, is there a way to put the vimeo id in a different form field when the video upload completes? I suspect gravity forms is filtering script looking values in the API as a security feature. I checked the database and the json is there, it just is not included in the entry object array.
