### ISSUE TITLE
Missing translation texts in POT file (Cannot translate)

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#13]
These texts are missing from wp-vimeo-videos-pro.pot file. So these cannot be translated:

![Képernyőfotó 2020-12-11 - 19 46 50](https://user-images.githubusercontent.com/39312392/101943758-f644f600-3beb-11eb-814a-98f70b82c130.png)
  
![Képernyőfotó 2020-12-11 - 20 10 14](https://user-images.githubusercontent.com/39312392/101945241-360cdd00-3bee-11eb-9e14-a40d421acaf7.png)

![Képernyőfotó 2020-12-11 - 20 20 00](https://user-images.githubusercontent.com/39312392/101945572-b29fbb80-3bee-11eb-9b08-9dfffa1c9d74.png)

"Filter" button text is missing from pot file.
"Filter by author" exists but it isn't translated to Hungarian:
![Képernyőfotó 2020-12-11 - 19 45 54](https://user-images.githubusercontent.com/39312392/101946557-66a14680-3bef-11eb-8646-845b9cc0c24e.png)

**Comment by gdarko** [comment]
Thanks @amroland  for the detailed screenshots. I will go through those and re-sync everything. Will keep you posted.

**Comment by amroland** [comment]
OK! Thanks!
🙂

**Comment by gdarko** [comment]
I believe this is fixed. Please open a new issue if anything else is missing. @amroland
