### ISSUE TITLE
Multiple video upload and Vimeo Live

### ISSUE THREAD

**Issue by ghost** [gdarko/wp-vimeo-videos#14]
Hi,

I purchase the Pro version of your plugin, and so far, working great! A couple of questions:

1. Is multi-file upload possible via Gravity forms? I've tried adding multiple file Upload fields on a form, and although I can select different Files, once the first Upload (button) is clicked, the rest of the (Ajax) buttons seem to upload, however only the first one is actually uploaded.

2. Any news on Vimeo Live implementation [as per this post](https://wordpress.org/support/topic/vimeo-live/) from a few months back?

**Comment by gdarko** [comment]
Hi @paulkiff ,

1. This should work normally unless there is a bug. I will check it and get back here.
2. Unfortunately there are no plans to add this feature yet unless there are more requests.

Best regards,
Darko

**Comment by ghost** [comment]
Thanks did the reply, gdarko.

When you mention that this should work normally on Gravity forms, do you mean multiple files can be selected in one upload Button/field? Or do we actually need different upload Buttons in the same form?

if the former, what will the files be named —if for example we select 5 video files and name the files (title) “Video test 01/07/2021”?

As you may imagine, this is a very important core feature since the upload lacks any visual cue of the percentage being uploaded or remaining.

Thanks

**Comment by gdarko** [comment]
Hi @paulkiff 

> if the former, what will the files be named —if for example we select 5 video files and name the files (title) “Video test 01/07/2021”?

This will not work, if it is possible to select multiple videos than this is a bug and will be resolved.

If you want to accept two videos, simply drop the "Vimeo Upload" field two times in the form or N times depending on how much videos you want to accept - this is the functionality that is supported for multiple uploads.

> As you may imagine, this is a very important core feature since the upload lacks any visual cue of the percentage being uploaded or remaining.

I am researching new ways to make this possible, probably there will be another Vimeo upload field with enhanced functionality in the next updates which will support progress bar.

Best Regards,
Darko

**Comment by paulkiff** [comment]
Thanks, gdarko

As per your above answer about dropping multiple “Vimeo Upload” fields in the form, how does the user uploads all after selecting the files or does the user needs to click on each Upload button separately?

A progress bar would be great as we plan to upload several HQ video files from users smartphones and they will feel lost after a few minutes go by without any visual indicator.

**Comment by paulkiff** [comment]
Hi gdarko,

No matter what, I can not get multiple files to upload. I've dropped several "Vimeo Upload" field on a Gravity form. On the front-end everything "looks" good, however, when selecting 4 or 5 files, only the first one is uploaded.

Do you mind checking on your end if this is working as expected?

**Comment by gdarko** [comment]
Hi @paulkiff ,

In version 1.6.0 we implemented progress bar for the front-end feel free to check it.

Best Regards,
Darko
