### ISSUE TITLE
Slow upload speed comparing to Vimeo Front-end uploader

### ISSUE THREAD

**Issue by ghost** [gdarko/wp-vimeo-videos#15]
Hi gdarko,

We were testing the Gravity form uploader (we were able to successfully setup multiple file upload.. thanks!) and uploading a 500Mb never finishes, while the same file uploaded via the Vimeo front-end uploader takes some 30 secs or so to finish.

I've modified our PHP settings as follows:

Quota	11.98 GB / 5 TB
Rate Limits	2 / 1000 per minute (resets on 2021-01-09 10:51:59)
PHP Version	7.4.12
Web Server	Apache
Max Upload Size	2048M
Max Post Size	2048M
Max Exec Time	0
Max Input Time	0

BTW, small videos (up to 50Mb or so) upload correctly; it's only the bigger videos having this issue.

**Comment by ghost** [comment]
In case it helps, I just checked on DevTools while uploading a "big" file and I get a POST 413 error message ( Payload Too Large?).

**Comment by gdarko** [comment]
Hi @paulkiff ,

To fix that problem you will likely need to increase the maximum request size in your web server configuration.

* Nginx example: `client_max_body_size 1000M` in the `nginx.conf`
* Apache example:  `LimitRequestBody 0` in the `apache.conf`

Best,
Darko

**Comment by gdarko** [comment]
Hi @paulkiff 

The upload speed is normal because it first uploads the video to the server and then the video is sent to Vimeo.

I can not include the front-end uploader on the front-end because the access token will be exposed to the wild and abusers can do whatever they want from your account using the access token.

Best,
Darko

**Comment by ghost** [comment]
> Hi @paulkiff ,
> 
> To fix that problem you will likely need to increase the maximum request size in your web server configuration.
> 
> * Nginx example: `client_max_body_size 1000M` in the `nginx.conf`
> * Apache example:  `LimitRequestBody 0` in the `apache.conf`
> 
> Best,
> Darko

Thanks so much, gdarko

Sorry to be a pain, but I've tried adding "LimitRequestBody 0" to my .htaccess to no avail. I keep getting the same POST 413 error message. I do understand this is my specific server configuration and not an issue with the actual plugin, however I need to get his demo to our client and sorta running out of options.

Any other ideas? 

BTW, I'm on AWS (Bitnami WP), if it helps.

**Comment by ghost** [comment]
> Hi @paulkiff
> 
> The upload speed is normal because it first uploads the video to the server and then the video is sent to Vimeo.
> 
> I can not include the front-end uploader on the front-end because the access token will be exposed to the wild and abusers can do whatever they want from your account using the access token.
> 
> Best,
> Darko

OK, that makes sense. I was under the impression that the plugin uploads directly to Vimeo (until I had my server's max size upload issues).

Thanks,

**Comment by gdarko** [comment]
Hi @paulkiff ,

In version 1.6.0 we implemented progress bar for the front-end feel free to check it :-)

Best Regards,
Darko
