### ISSUE TITLE
Video file format(s)

### ISSUE THREAD

**Issue by ghost** [gdarko/wp-vimeo-videos#17]
Hi Gdarko,

What file types are supported by the plugin? I tried uploading an .MTS video file (supported by the Vimeo uploader), however Gravity forms show a "Uploaded file types are not supported" error message. 

I was under the impression that the uploader supports all file types supported by Vimeo?

**Comment by gdarko** [comment]
Hi Paulkiff,

I will check this, it's probably this .mts extension is excluded by the validations.

I plan to release version 1.5.6 today/tomorrow and will include it.

Best Regards,
Darko

**Comment by ghost** [comment]
Great, thanks so much, Gdarko.

**Comment by ghost** [comment]
Hello GDarko,

Any news on 1.5.6?

**Comment by gdarko** [comment]
Hi @paulkiff 

The new version is now released. Sorry, it took some time to test everything.

Best Regards,
Darko
