### ISSUE TITLE
Additional questions

### ISSUE THREAD

**Issue by arnerotty** [gdarko/wp-vimeo-videos#2]
Hy Darko,

I bought the PRO version yesterday, and up untill now i'm quite impressed with the tool.
I was wondering if you could help me out with these 3 questions: 

- Can you elaborate a bit on how exactly I can add 'tags' to the file upload function?
-How can I pull the video's back from my account at vimeo back to the front end so I can setup a video stream?
- I i'm able to pull the video's from my account, would it be possible to filter though them based on the tags?

Best regards,

Arne

**Comment by gdarko** [comment]
Hi Arne,

Hope you are well.

1.) By tags you mean to tag the video on Vimeo.com or in the WordPress database upon upload?
2.) This is not possible at this time.
3.) This is not possible at this time.

Best,
Darko

**Comment by gdarko** [comment]
Closed for inactivity. If you have more questions feel free to ask us at info@codeverve.com
