### ISSUE TITLE
Hide Settings > Vimeo menu for Administrators in Multisite

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#22]
Dear Darko,

I suggest a new setting:
Hide Settings > Vimeo menu for normal Administrators in Multisite. (Only Super Administrator can see it.)

I am running a Multisite WP where users with normal Administrator role should not see Settings > Vimeo menu. Only users with Super Administrator role should see it.
You could implement it to settings.

Thanks,
Roland

**Comment by gdarko** [comment]
Hi @amroland ,

Hope you are doing well. Feel free to message me at info@codeverve.com and list all the websites you are currently using, so i can safely deactivate the key on the others.

Regarding the Vimeo Settings, in the next version I will try to add something to control the Setting, possibly a filter.

Best Regards,
Darko

**Comment by amroland** [comment]
Dear @gdarko,

This issue hasn't solved.
