### ISSUE TITLE
User filter not working

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#23]
Dear Darko,

I tried user filter on Media > Vimeo screen, but it wasn't working.

I started to enter some 3 letters, but no results was found.
Screenshot:
![Képernyőfotó 2021-03-01 - 14 21 50](https://user-images.githubusercontent.com/39312392/109505872-52a60c00-7a9d-11eb-9905-da2d592ce7f1.png)

Can you check it?
Thanks,
BR,
Roland

**Comment by gdarko** [comment]
@amroland 

Hi, It works however i need to tweak it, i think it requires more characters than 3.

Will check this.

Thanks.

**Comment by amroland** [comment]
Hi,

I checked it once more. You have to enter the whole username to give you result. It doesn't work with fewer character.
For example:

With "pallimola" username only "pallimola" will give you result. But "pallimol" doesn't give you result:
![Képernyőfotó 2021-05-26 - 11 53 45](https://user-images.githubusercontent.com/39312392/119640582-0d357880-be19-11eb-856b-e99fea6fbef9.png)
![Képernyőfotó 2021-05-26 - 11 53 38](https://user-images.githubusercontent.com/39312392/119640612-145c8680-be19-11eb-81eb-3b34491b96ec.png)

With "galanett72" username only "galanett72" will give you result. But "galanett7" doesn't give you result:
![Képernyőfotó 2021-05-26 - 11 54 34](https://user-images.githubusercontent.com/39312392/119640792-3fdf7100-be19-11eb-8dec-60d11187be76.png)
![Képernyőfotó 2021-05-26 - 11 54 42](https://user-images.githubusercontent.com/39312392/119640810-44a42500-be19-11eb-91a4-472d3f7b6152.png)

And it is also strange that the result is always the Public name of the user. Not the Username.

BR,
Roland

**Comment by amroland** [comment]
Dear Darko,

In version 1.7.1 I can see this fix:
Fixed author filter in tinymce / gutenberg upload modal when show videos of current author option is enabled.

Isn't that about this issue, is it?

BR,
Roland

**Comment by gdarko** [comment]
Hi @amroland ,

No, this one is coming in the next update once i finish with testing.

> Fixed author filter in tinymce / gutenberg upload modal when show videos of current author option is enabled.

This is a problem that I found when editing as a non-admin user in the Gutenberg/TinyMCE editor it was showing other videos uploaded by other authors, even if that option is enabled in settings.

**Comment by gdarko** [comment]
This is fixed in the upcoming release that will be released tomorrow.
