### ISSUE TITLE
Don't have "Vimeo" button on frond-end TinyMCE Editor

### ISSUE THREAD

**Issue by FunkkyMonkeyy** [gdarko/wp-vimeo-videos#27]
Hello sir,
I'm using a WP Vimeo Videos Pro lasted version, v1.7.0, but right now, in my front-end TinyMCE Editor, I don't see anything but in your description you have it. Does it have to activate automatically or do I have to activate it manually with wp_editor() in the functions.php , and what code do I have to do that if I have to activate it manually? Please help me in soon, thank you

**Comment by gdarko** [comment]
Hi @FunkkyMonkeyy ,

Can you please message us at info@codeverve.com with more details and please include login details to check the issue.

Best Regards,
Darko

**Comment by FunkkyMonkeyy** [comment]
Thanks for reply me and your assistance @gdarko 
Also, Sorry for my late response for you
Now i find issue for my page, my theme i'm use now, it's use VueEasyTinyMce, one offer for Vue.js in this case, and i find the issues don't have in front end because it's don't have name plugins in it, show you can talk to me about slug of your plugins so i can add this to front end
If you want to know more about VueEasyTinyMce and the slug I can add to VueEasyTinyMce you can check it out on github below:
https://github.com/m3esma/vue-easy-tinymce

Best Regards.

**Comment by gdarko** [comment]
The WP Vimeo Videos only supports the native WordPress tinymce.
