### ISSUE TITLE
Video upload doesn't work

### ISSUE THREAD

**Issue by codingspook** [gdarko/wp-vimeo-videos#29]
![Schermata 2021-06-09 alle 11 56 45](https://user-images.githubusercontent.com/65157104/121334238-c74cda00-c919-11eb-8c28-ee238c150bab.png)

Hi, i can't find out how upload doesn't work anywhere (Media > Vimeo or Gravity Form field).

Can you help me with this please? I'm pretty sure that i had correctly configured the plugin.

Thank you

**Comment by gdarko** [comment]
Hi @mdicampli,

Can you contact me by [email](mailto:info@codeverve.com) please and send details to the site so I can check.

Thanks.

**Comment by gdarko** [comment]
Closed for inactivity.
