### ISSUE TITLE
Activation/deactivation issues.

### ISSUE THREAD

**Issue by darionco** [gdarko/wp-vimeo-videos#3]
Hello,

I am working with a client that purchased the plugin and is switching domains, neither the new domain nor the old domain seem to have the plugin activated. I have access to the purchaser's account on codeverve.com and everything seems to be ok there.

Is there a way to deactivate the old installation and free the license up for a new activation?

also, I will be using a staging server to work for my client so I will need to be able to temporarily activate the licence in the staging server, then deactivate it and activate it in the production server once the code is ready to be deployed. Is this possible?

Thank you.

**Comment by gdarko** [comment]
Hi Dario,

Can you send me the purchase code?

Thanks

**Comment by gdarko** [comment]
Hi @darionco 

Can you email us the purchase code at info@codeverve.com for further assistance?

Thanks

**Comment by darionco** [comment]
Sure, the code is:
```
#687
```
e-mail sent with all info.


Thanks!

**Comment by gdarko** [comment]
Hi @darionco ,

This is now done. Thanks for the patience.

Best,
Darko
