### ISSUE TITLE
What Does it add to the Post

### ISSUE THREAD

**Issue by AndyNeedham01** [gdarko/wp-vimeo-videos#30]
Hi,

I'm thinking of buying this product - pro version.

If I upload a video to Vimeo using this upload what information does it add to the post / database?

Does it add the URL where the video can be viewed?

I use Elementor and it works with a URL

Also, any chance of this working with Crocoblock JetEngine forms?

Thanks

**Comment by gdarko** [comment]
Hi @AndyNeedham01 ,

1.) It inserts `[dgv_vimeo_video id="the_vimeo_id"]` shortcode and that shortcode prints out the vimeo embed markup. It can also be modified to show just a link (oEmbed) with a filter as follow:

```php
/**
 * Outputs vimeo link instead of vimeo embed markup
 * @param $content
 * @param $vimeo_id
 *
 * @return string
 */
function dgv_shortcode_output_818281281($content, $vimeo_id) {
	return sprintf('https://vimeo.com/%s', $vimeo_id);
}
add_filter('dgv_shortcode_output', 'dgv_shortcode_output_818281281', 10, 2);
```

2.) Currently, it doesn't support Crocblock JetEngine forms, but I will take a look and see if I can integrate it in one of the future versions.

Best Regards,
Darko

**Comment by gdarko** [comment]
Moved to our private issue tracker
