### ISSUE TITLE
Video upload problems

### ISSUE THREAD

**Issue by jykkema** [gdarko/wp-vimeo-videos#31]
Uploading from admin area works great. Video is visible on Vimeo.com.

When using Gravity Forms and Vimeo upload, everything goes ok, I can see video added from admin area.
When I go to Vimeo.com or use Vimeo link from admin area, video says uploading.
Even I wait hours, video wont be ready.

I have tried modern and classic Vimeo upload on Gravity Forms.

**Comment by gdarko** [comment]
Hi @jykkema,

Thanks for your message.

I will need to take a look at your environment, can you please send me details of the site via [email](mailto:info@codeverve.com).

Thanks.

**Comment by jykkema** [comment]
@gdarko 

Thanks, done.

-jykkema
