### ISSUE TITLE
Front-end upload doesn't work

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#32]
Hi Darko,

I have tried to upload on front-end. It doesn't work through Gravity forms Modern or Classic mode. And it doesn't work through Gutenberg WP Vimeo Upload, too. These videos are just uploading-uploading in Vimeo account.
Uploading only works through admin site (Media » Vimeo).
(I tested it logged in and also logged out in incognito mode. "tehen" means "cow" in Hungarian.)
![Képernyőfotó 2021-06-10 - 10 24 32](https://user-images.githubusercontent.com/39312392/121492431-29b7e000-c9d7-11eb-9f9a-53b2cf869322.png)
![Képernyőfotó 2021-06-10 - 10 24 51](https://user-images.githubusercontent.com/39312392/121492439-2c1a3a00-c9d7-11eb-828d-3ee3f1277f7c.png)

Modern upload site: https://tanula.hu/video-modern-upload/

Classic upload site: https://tanula.hu/video-classic-upload/

Gutenberg WP Vimeo upload site: https://tanula.hu/video-gutenberg-upload/

By the way:
Gutenberg upload site is very strange. On its edit page I can see many settings:
![Képernyőfotó 2021-06-10 - 10 31 54](https://user-images.githubusercontent.com/39312392/121492620-4eac5300-c9d7-11eb-982f-065f49c7681d.png)
But on front-end it says: "No video uploaded." And it doesn't show any form to upload:
![Képernyőfotó 2021-06-10 - 10 23 11](https://user-images.githubusercontent.com/39312392/121492783-756a8980-c9d7-11eb-8262-23a9c048a2dd.png)

Can you, please help me?
Thanks!

BR,
Roland

**Comment by gdarko** [comment]
Hello @amroland,

This issue with GravityForms integration was resolved in version 1.7.2 (released yesterday).

Can you please update to 1.7.2 of the PRO version and then check again. 

Best Regards,
Darko

**Comment by gdarko** [comment]
@amroland ,

Regarding the Gutenberg block, can you please send me a console screenshot or email me so we can discuss this further.

Thanks

**Comment by amroland** [comment]
Dear @gdarko,

Version 1.7.2 really resolve Gravity forms front-end issue.
Thanks!

Regarding Gutenberg block, I send you an email directly.

BR,
Roland
