### ISSUE TITLE
Delete doesn't work

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#34]
Hi Darko,

Delete link doesn't delete the video from Vimeo account:
1, There is an uploaded video on admin site:
![Képernyőfotó 2021-06-10 - 11 51 40](https://user-images.githubusercontent.com/39312392/121504431-4c032b00-c9e2-11eb-9fba-ba25abe9363d.png)
It is listed on Vimeo, too:
![Képernyőfotó 2021-06-10 - 11 51 57](https://user-images.githubusercontent.com/39312392/121504499-59201a00-c9e2-11eb-975e-830d94ddb147.png)
2, I delete it from admin site:
![Képernyőfotó 2021-06-10 - 11 53 04](https://user-images.githubusercontent.com/39312392/121506404-f62f8280-c9e3-11eb-8759-911eb01da804.png)
And this pop-up window appears:
![Képernyőfotó 2021-06-10 - 11 53 21](https://user-images.githubusercontent.com/39312392/121506507-10696080-c9e4-11eb-9982-10c9389bcbaa.png)
And the video is still on Vimeo account:
![Képernyőfotó 2021-06-10 - 11 54 45](https://user-images.githubusercontent.com/39312392/121506553-1c552280-c9e4-11eb-989a-b55e01f0fa0c.png)

BR,
Roland

**Comment by gdarko** [comment]
Hi @aroland,

Do you have the "delete" scope enabled for your API token?

Please check Settings page to view the enabled scopes.

Best Regards,
Darko

**Comment by amroland** [comment]
Hi @gdarko,

I have set these API app settings for about 2 years and I didn't change anything. I checked it now and as I expected it, everything is OK:

Scopes | private, create, edit, delete, interact, upload, video_files, public

**Comment by gdarko** [comment]
I will revisit this function for the next version, some other users reported similar issues.

Thanks for the info.

**Comment by gdarko** [comment]
This is fixed in the new version which will be released this coming week, possibly tomorrow. @amroland
