### ISSUE TITLE
Clicking on Author goes to logged in user's profile

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#35]
Hi Darko,

As an administrator I can see everyone's uploaded videos on Media » Vimeo page.
If I click on a different author than me, it direct me to MY profile page. Not to his/her profile.
![Képernyőfotó 2021-06-10 - 14 38 40](https://user-images.githubusercontent.com/39312392/121526916-297d0c00-c9fa-11eb-9acc-91fc9f350ff0.png)

The link is always: /wp-admin/profile.php

It is not a problem for me, but I thought I inform you about this.

BR,
Roland

**Comment by gdarko** [comment]
Fixed in the new 1.7.3 version
