### ISSUE TITLE
Admin screen on front end?

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#39]
Hi Darko,

Is there a way to display your plugin's admin interface/screen on the front end for a logged in user?
There should be a new menu item on My Account area where you can see a list of your own uploaded videos just as if you are able to see it in the admin interface/screen.
For example:
![Képernyőfotó 2021-08-22 - 17 00 45](https://user-images.githubusercontent.com/39312392/130360198-69db908b-7fe6-4a49-a9ac-bc5f216ce0d6.png)

Thanks,
Roland

**Comment by gdarko** [comment]
This is already work in progress, however, i am working on a shortcode that displays a table of videos on the front-end and allows the user to edit or delete video or even upload a video - it will be possible to embed it anywhere.

@amroland

**Comment by amroland** [comment]
Dear @gdarko ,

That's great! When is this expected to be completed?
Roland

**Comment by amroland** [comment]
Dear Darko,
Can I ask you, what the status of this development is?
Thank you!

**Comment by gdarko** [comment]
In the new 2.0.0 version there will be shortcode and gutenberg block for this.

Related #85
