### ISSUE TITLE
Missing translation texts in POT file

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#41]
"The requested video couldn't be found." text is missing in POT file.
Cannot be translated.
It is a notification text which appear when a video is deleted from admin site, however the actual video had been deleted from Vimeo previously.

![Képernyőfotó 2021-12-01 - 10 42 09](https://user-images.githubusercontent.com/39312392/144211184-baf18842-c3bd-4f3d-b9cb-82d4488db00b.png)

"Save Settings" text is also missing in POT file.
It is a button text on WP Vimeo Settings page.

**Comment by gdarko** [comment]
Hi @amroland 

Regarding "The requested video couldn't be found" - this text is received from Vimeo and is impossible to translate with i18n system that WordPress uses.

Regarding "Save Settings" - this is already done and will be available in our next release.

Best Regards,
Darko
