### ISSUE TITLE
Bulk actions like remove (suggestion)

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#42]
It would be good feature if bulk actions can be used on admin page like delete videos from Vimeo.
There should be check boxes at the beginning of each line with which you can select more videos to delete from Vimeo.

**Comment by gdarko** [comment]
Hi @amroland ,

Thanks for the suggestion.

I will consider this for the next 1.8.0 which is coming soon. It will include general admin table improvements and I am planning to add Video categories.

Best Regards,
Darko
