### ISSUE TITLE
Front-end form submission - getting vimeo url

### ISSUE THREAD

**Issue by chrslcy** [gdarko/wp-vimeo-videos#43]
Front-end form submission with gravity forms is working fine, but I would like users to be presented with the vimeo url, just as happens when uploading via admin. Is this possible?

Thanks,

Chris

**Comment by gdarko** [comment]
Hi @chrslcy ,

Which front-end integration you are using GravityForms or WPForms?

It is also possible to integrate the Vimeo uploader that you see in the admin editors anywhere by following this Gist
https://gist.github.com/gdarko/61b75a9709492054b90227801bb352fb

Best Regards,
Darko

**Comment by chrslcy** [comment]
Hi @gdarko,

Thanks for the prompt reply. I'm using Gravity Forms.

Here's my attempt with a gravity form:
https://schoolsays.co.uk/ video-upload/ (remove the space)

Here's my attempt with your gist:
https://schoolsays.co.uk/ video-upload-gist/ (remove the space)

Neither displays the vimeo url where the video has been uploaded.

Thanks,

Chris

**Comment by gdarko** [comment]
Hi Chris,

1. Regarding the Gravity Form integration, you can only display the URL after the form submission at this time. To do this, go to GravityForms > Confirmations > Add New.

![image](https://user-images.githubusercontent.com/5760249/144418118-9aaf83b4-e7c3-477c-a8dc-e28541dc9738.png)


2. I checked your gist code (https://schoolsays.co.uk/wp-vimeo-videos-pro/script.js) - and you are missing a div in your markup that will be used to display the url with this code: ` $('#vimeo-url').text(uri); `

To resolve this add a div as follows somewhere in your markup `<div id="vimeo-url"></div>`

Let me know if this helps.

**Comment by chrslcy** [comment]
Thanks again for your quick support. I managed to get both working. For the gist version, I already had a p element on the page like this:

`<p id="vimeo-url"></p>`

..but it didn't work until I changed it to a DIV. Not sure why. However, I will stick with the Gravity solution as it is more suitable for my purposes.

Thanks again!

Chris

**Comment by gdarko** [comment]
Perfect @chrslcy 

Closing this now.
