### ISSUE TITLE
Suggestion: Duration column

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#47]
I can see that database contains duration of each uploaded video. I suggest that there should be a Duration column on uploaded videos list screen to be more able to identify each video.
and
Happy New Year, Darko!

**Comment by gdarko** [comment]
Hi @amroland - 

I will delay this for future version for which i want to implement Vimeo sync process that will periodically check using cron task the locally stored videos against the vimeo API and gather details like duration, size,etc or remove if it doesn't exists on vimeo.com

Currently the duration is determined once you visit the video "Manage" page in the admin size lazily, however this was rather experimental feature in 1.7.0 series that it's aim was to gather as much as possible data for expanding the interfaces in the future version. As i said i have to complete the sync process and then we will be sure that we have the data all the time up to date.

Best,
Darko

**Comment by amroland** [comment]
Hi @gdarko,

Of course it's not the most important feature. I just suggested it to you.

Vimeo sync process with using cron is awesome!!!!

What most important for me now is this issue: https://github.com/gdarko/wp-vimeo-videos/issues/51
Can you look at it?
