### ISSUE TITLE
Need product key

### ISSUE THREAD

**Issue by InvincibleRanch** [gdarko/wp-vimeo-videos#5]
Purchased Pro but can't find the product key anywhere.
Order Number / Receipt: #18004161
Billing date: 23 Sep 2020

Thanks

**Comment by gdarko** [comment]
Hello @InvincibleRanch 

I noticed this on some orders. I re-dispatched the emails. Can you let me know if you received it now?

Also, feel free to contact us at info@codeverve.com if you sharing more sensitive information.

Thanks

**Comment by InvincibleRanch** [comment]
Hi @gdarko, got it. Thanks.
