### ISSUE TITLE
Suggestion: Video size refresh (manual) button or automatic synchronization

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#50]
There could be a button, which syncs videos actual sizes from Vimeo.
It would be useful if you REPLACE any video on Vimeo site. And it would be also useful to fill/refresh sizes of videos, which was uploaded before size column was implemented to WP Vimeo Videos PRO (1.7.0.). "Not available":
![Képernyőfotó 2021-12-31 - 22 14 37](https://user-images.githubusercontent.com/39312392/147839180-6fc99d1d-19cd-4fe5-8e12-d38a27e25bc9.png)

I noticed that video description is automatically syncs if you change it through Vimeo site. Somehow it syncs immediately on WordPress site. (API?)
It would be good if you can implement it in case of replacing video to a new one.

**Comment by gdarko** [comment]
Hey @amroland , 

Unfortunately the Vimeo API does not return anything related to the size, so we have to rely on the upload file size for now.

I am happy to reconsider this in future in case Vimeo API starts supporting it.

Best Regards,
Darko
