### ISSUE TITLE
Important: Editors cannot see all of their videos (more than 20 pcs)

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#51]
Hi Darko!

Our users (with editor role) have drawn our attention that they cannot see all of their uploaded videos (more than 20 pcs).

I checked and it's true:
If an Editor has got more than 20 videos uploaded, he/she cannot see just the first 20 pcs without any pagination.
If you add &paged=2 , &paged=3, etc to URL, it shows the rest of them, but pagination is still not visible.

For some reason, pagination doesn't appear on uploaded video list screen if you have Editor role.

Can you take a look at it?
Thank you very much!

**Comment by gdarko** [comment]
@amroland - the new version is now released.

**Comment by amroland** [comment]
Dear Darko,

Yes, I already know it. Furthermore, I am very happy about it.
I already wanted to thank you, but thought, I wouldn't bother you right now. You should have enough work to do.
But of course I thank you!
