### ISSUE TITLE
How to use PRO features

### ISSUE THREAD

**Issue by hirobel** [gdarko/wp-vimeo-videos#54]
I purchased PRO License.

「Video Uploads for Vimeo Settings」 is already installed on WordPress.
I don’t figure out where to input lisence key to use PRO features

**Comment by gdarko** [comment]
Hi @hirobel 

You need to log in to https://codeverve.com/my-account with the email address that you purchased the product and then go to "Licenses" tab. Click on the license you purchased and at the bottom, you will see "Downloads" section.

Let me know if you have any difficulties.

Best Regards,
Darko

**Comment by hirobel** [comment]
@gdarko 

Thank you for rapidly reply!
I understanded how to download it.

I'm exciting to develop web app by wp-vimeo-videos today!

**Comment by Shajeel-Afzal** [comment]
@gdarko I am also facing this problem, I have purchased the Pro Version however I am not sure where to download the Pro Version! I don't see the download button after going the link that you have specified, All I see the key.

**Comment by gdarko** [comment]
Hi @Shajeel-Afzal 

1. Login to the site in https://codeverve.com/my-account
2. Go to Licenses tab
3. Open the purchased License
4. Scroll down to the bottom to download the pro version.
5. Deactivate FREE version and Upload/Activate PRO to your site

Best Regards,
Darko
