### ISSUE TITLE
Bulk delete does not work (fix provided)

### ISSUE THREAD

**Issue by PSalaun** [gdarko/wp-vimeo-videos#55]
In Media/Vimeo, the bulk action "Delete" does not work because the uri sent to Vimeo API doesn't contain the `/videos/` part.

To fix it (for Vimeo Pro), change the line 379 in class-wp-dgv-list-table.php from : 
`$vimeo_uri = $this->db_helper->get_vimeo_uri( $record );`
to
`$vimeo_uri = wvv_id_to_uri($this->db_helper->get_vimeo_uri( $record ));`

It's a quick and dirty fix, as I understand get_vimeo_uri should return the right format.

**Comment by gdarko** [comment]
This is fixed in 1.8.1

Thanks for reporting.
