### ISSUE TITLE
Gravity Forms frontend upload doesn't complete (fix provided)

### ISSUE THREAD

**Issue by PSalaun** [gdarko/wp-vimeo-videos#56]
When uploading a video from Gravity Forms (modern or classic) with WP Vimeo Videos Pro v1.8, the background task to upload the video keeps failing and therefore the video is created in Vimeo but stuck on the "Uploading" step.

The culprit is Guzzle, and it can be fixed by updating this package to 7.4.2 (including its dependencies, using `composer update guzzlehttp/guzzle -W`)

**Comment by gdarko** [comment]
This is fixed in 1.8.1
