### ISSUE TITLE
Inactive video name could confuse users by using "Insert Vimeo video from local library" option

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#57]
Choosing "Insert Vimeo video from local library" option in WP Vimeo upload block could confuse users a bit.

Selecting this option will immediately show the first insertable video name, but with an inactive color.
When clicked into drop-down menu, the full list of videos is displayed correctly. "Select existing video" text is also displayed at the top of this list.
![Képernyőfotó 2022-04-05 - 13 06 45](https://user-images.githubusercontent.com/39312392/161742907-e58e1eb6-90ca-41c7-9af5-08a60142d5b3.png)

The very first video can only be selected by selecting another one and after that selecting the first one again. Video player window of this video only appears after this.
I don't know how it works if a user has got only one video. Perhaps it doesn't work?!?

I suggest that when you select "Insert Vimeo video from local library" option, the "Select existing video" text should be active and selected instead of an inactive video name.

**Comment by amroland** [comment]
Hi Darko,
I tried it with only one uploaded video. And it doesn't work.
The first (and only) video is being selected but after Publish (or preview) the post the video isn't embedded:
![Képernyőfotó 2022-07-05 - 8 55 41](https://user-images.githubusercontent.com/39312392/177268890-1f0771d2-ba3d-480f-9b34-b18ea62b75cb.png)

On the editor screen of the post WP Vimeo Upload block shows the inactive (and the only) video, but it can not embed anyway:
![Képernyőfotó 2022-07-05 - 8 55 55](https://user-images.githubusercontent.com/39312392/177269263-2b0536b7-5d87-4b9f-a542-3b58243853c3.png)

**Comment by gdarko** [comment]
Fixed in the new incoming v1.9.2
