### ISSUE TITLE
Upload via gravityform not working

### ISSUE THREAD

**Issue by EthanCG** [gdarko/wp-vimeo-videos#59]
Hi,
Currently testing your plugin and uploading from media library work but uploading from a gravityform doesn't.
Standard field display and can pick a file.
Modern field doesn't work at all, display pictogram but no area active.

Any clue ?
My WP is running on latest version, on Linux 4.14.253/Apache/php 7.4.25/ cURL 7.64.0 OpenSSL/1.1.1d , no console error

**Comment by gdarko** [comment]
Hey @EthanCG ,

I am happy to help on this. Can you please contact me on info@codeverve.com and provide me temporary wp login to test?

Best Regards,
Darko

**Comment by gdarko** [comment]
Closed for inactivity
