### ISSUE TITLE
Suggestion: Total uploaded size per users

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#61]
I suggest that there could be a counter on the list page that shows the total size of all videos uploaded by the GIVEN user.
This could be solved if the wp_users or wp_usermeta table in the database contained an uploaded-total-size variable for each users.
When a user is uploading a video, a process should increase the value of this variable by the size of the uploaded video.
On deletion, a process should decrease the value of this variable.

It would be also important to be able to somehow synchronize this variable due to possible incorrect calculations. A synchronization button could be used to request the size of all the videos of the given user, and rewrite the value of this variable in the database.

This is how I imagine this:
![Képernyőfotó 2022-08-21 - 13 31 32](https://user-images.githubusercontent.com/39312392/185789375-a99461a3-5654-465a-a791-3f143eae3e73.png)

**Comment by amroland** [comment]
Hi @gdarko,

will this function be implemented soon?

**Comment by gdarko** [comment]
Hey @amroland 

It's possible but this feature will work only with the available data. At this time there is no way to obtain the file size from vimeo, so we have to rely on the size that we store on upload.

It's related to this
https://github.com/gdarko/wp-vimeo-videos/issues/50

**Comment by amroland** [comment]
Hi @gdarko 
Then it will be fine. Can you implement this file size summary using the size data in the database?
(The Vimeo file size synchronization can still wait.)
