### ISSUE TITLE
Suggestion: Description column

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#68]
It is just a suggestion:
There should be a Description column on uploaded Vimeo video list page (Media library » Vimeo).

If you upload couple of videos with almost the same content, description section is the right tool to remind yourself exactly what the video is about. Unfortunately, title of video is too short.
But Vimeo list page doesn't contain description column.

I imagine that it would be sufficient to display only some (eg 100) characters of text, followed by "...", which, when clicked, would display the full description.

**Comment by amroland** [comment]
Hi Darko,

Firstly let me congratulate you on version 1.9.3. Great! Super!

However, I notice that the "Show Description" feature on Screen Options does not work. Does not display the Description column in the table.
![Képernyőfotó 2023-03-07 - 10 27 52](https://user-images.githubusercontent.com/39312392/223381343-4148120e-62c1-4449-858d-e92ad51e545d.png)

**Comment by gdarko** [comment]
Hey @amroland  - It should show under the Title if you entered a description. No separate column for the description.

**Comment by amroland** [comment]
But it doesn't appear there either:
This video has got Description:
![Képernyőfotó 2023-03-07 - 10 49 19](https://user-images.githubusercontent.com/39312392/223386102-59d85aef-566d-4671-a32b-e43cfb2b0544.png)

In list table:
![Képernyőfotó 2023-03-07 - 10 27 52](https://user-images.githubusercontent.com/39312392/223386303-c853db60-3067-4844-b981-d11bea59eeef.png)

**Comment by amroland** [comment]
It is strange. Now I uploaded a new video WITH description and it appears in table. But the previous video which description was set lately, after uploading, hasn't got description in the table:
![Képernyőfotó 2023-03-07 - 10 52 52](https://user-images.githubusercontent.com/39312392/223387313-02e230c1-bd94-453f-947a-16c60a68f10a.png)
