### ISSUE TITLE
Uploading via Gravity Forms not working

### ISSUE THREAD

**Issue by richardpeng** [gdarko/wp-vimeo-videos#7]
The videos I upload via Gravity Forms always end up 0 seconds and transcoding forever. This is what my Gravity Form configuration looks like:

<img width="515" alt="LWScreenShot+2020-10-16+at+2 47 19+PM" src="https://user-images.githubusercontent.com/430409/96297230-8b49bb00-0fbe-11eb-925d-0252c9be5c11.png">

**Comment by gdarko** [comment]
Hi @richardpeng,

If you still have the problem please contact us at info@codeverve.com and create temporary login to the site so we can inspect in details.

Best,
Darko
