### ISSUE TITLE
"Only those with link" (=Unlisted) settings doesn't show video (Sorry This video does not exist.)

### ISSUE THREAD

**Issue by amroland** [gdarko/wp-vimeo-videos#74]
If you set Privacy settings to "Only those with link" (=Unlisted), video is not visible on its editor page. It says:
Sorry
This video does not exist.

![Képernyőfotó 2023-03-06 - 9 36 21](https://user-images.githubusercontent.com/39312392/223060877-ff9ddffc-dd09-4d3f-a20f-a2149f930a8e.png)

With Unlisted settings you can embed your video anywhere, so video should be visible.
I think the problem is, that after setting Privacy to Unlisted, link of given video is changing (it gets a slash and a couple of numbers behind it). And the upper video player window doesn't get its new link to be able to show video.

**Comment by amroland** [comment]
Isn't this fixed in 1.7.0?!?
"- Fixed a bug when the view privacy is 'Only those with link'. Video links were pointing to wrong link, instead of private video link"

**Comment by gdarko** [comment]
Hey @amroland  - i will check this and get back to you asap.

**Comment by amroland** [comment]
I think I figured out what the problem might be. Your own shortcode (dgv) does not handle well if the video_id uses this longer Vimeo link format, which comes out in the case of "Anyone with link" privacy setting.

![Képernyőfotó 2023-03-10 - 12 29 00](https://user-images.githubusercontent.com/39312392/224304898-b268476c-1b9a-49a0-b6e9-6ea14683cfdc.png)


Can you tell me when you could fix this?
Because it would be nice if the uploaded video could also be seen in the case of "Anyone with link":
- On the video's editing page
- On the page that opens by clicking the "View" button

**Comment by amroland** [comment]
Dear @gdarko,

Do you know, when this issue will be fixed?
Thanks!
