### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by directingchange** [gdarko/wp-vimeo-videos#8]
I'm getting an error uploading videos from my site. (select Submission Format - Video PSA)

https://www.directingchangeca.org/entry-form-hope-justice-category/

The error is:
"Sorry, the current remaining quota in the Vimeo account is 0 B and this file is 32.9826 MB. Therefore the video can not be uploaded because the Vimeo account doesn't have enough free space."

I've checked with Vimeo and there is no limit I'm reaching on their side.

**Comment by gdarko** [comment]
Hi @directingchange,

There will be new version 1.5.0 release tomorrow (Monday) which will fix any problems related to it or add warnings about possibly missing scopes.

Also, can you check your scopes in the Settings screen?

You need to have the following scopes at least:

- create
- interact
- video_files
- private
- edit
- upload
- delete
- public

If you are missing scopes, please go to Vimeo Developer portal, select your existing APP, delete your old access token, create new access token and select those scopes. Input the new access token in the Settings screen.

Best,
Darko

**Comment by directingchange** [comment]
I updated to the latest version and created a new access token with all the scopes.  Still getting the same error.

"Sorry, the current remaining quota in the Vimeo account is 0 B and this file is 11.9295 MB. Therefore the video can not be uploaded because the Vimeo account doesn't have enough free space."

**Comment by gdarko** [comment]
@directingchange  please send us an email with login credentials to the site and we will check.

Use this email info@codeverve.com

**Comment by directingchange** [comment]
I sent credentials.

Here is a page to test with

https://www.directingchangeca.org/test-video/

thank you!

**Comment by gdarko** [comment]
@directingchange , Thanks.

We found out that you are using customized plan of the Vimeo PRO  which was not supported in our plugin.

We released a new version v1.5.1 which brings support for "Vimeo PRO Unlimited". Also i updated it on your site and it works now.

Best,
Darko

**Comment by directingchange** [comment]
Great, thank you
