### ISSUE TITLE
upload video to vimeo by wp-forms

### ISSUE THREAD

**Issue by stefanoalmonte** [gdarko/wp-vimeo-videos#84]
upload video to vimeo by wp-forms not work
please help me

this is link:

https://beta2.formazi.one/vimeo-upload/beta2/

**Comment by gdarko** [comment]
Hey @stefanoalmonte ,

 Can you contact us at info@codeverve.com with your purchase email.

**Comment by stefanoalmonte** [comment]
yes
email is ***@***.***

the problem is that i dont'want click video for upload to vimeo but i need
automations...
sorry for my english...


Il giorno mer 12 lug 2023 alle ore 11:58 Darko Gjorgjijoski <
***@***.***> ha scritto:

**Comment by stefanoalmonte** [comment]
I Darko ... please i need help ... I bought the plugin but I have problems ... thanks ...

**Comment by stefanoalmonte** [comment]
I Darko ... Why do not you answer?

**Comment by stefanoalmonte** [comment]
I Darko ... Why do not you answer?

Il giorno gio 13 lug 2023 alle ore 09:10 stefano almonte lalli <
***@***.***> ha scritto:

**Comment by gdarko** [comment]
Hey, 

I wrote a message to your email just now. Let's keep the communication here.

Best Regards,
Darko

**Comment by stefanoalmonte** [comment]
ok
the problem is that I can't upload the video to vimeo after uploading it from the form, going to the list and clicking upload. I need it to happen automatically… thanks.

**Comment by gdarko** [comment]
Ok, thanks i got it. 

I do have some questions, so make sure you saw the email i wrote on staff@astrellia.it and let's keep the discussion on that email, please!

**Comment by stefanoalmonte** [comment]
ok

**Comment by stefanoalmonte** [comment]
Sure, no problem.

Il giorno mer 19 lug 2023 alle ore 15:13 Darko Gjorgjijoski <
***@***.***> ha scritto:

**Comment by stefanoalmonte** [comment]
Hey Darko ... i'am waiting ... please ...

Il giorno mer 19 lug 2023 alle ore 15:15 stefano almonte lalli <
***@***.***> ha scritto:

**Comment by gdarko** [comment]
Hey, Can you check your email? I sent details here.
[staff@astrellia.it](mailto:staff@astrellia.it)

**Comment by stefanoalmonte** [comment]
Hey Darko, we provided you with login credentials on July 12th.
Please communicate via the email address ***@***.*** because
staff is reception only ...
thank you.

Il giorno mer 19 lug 2023 alle ore 17:11 Darko Gjorgjijoski <
***@***.***> ha scritto:

**Comment by gdarko** [comment]
The issue has been solved. Closing.
