### ISSUE TITLE
Upload from front end via Gravity Form is not working, says out of quota

### ISSUE THREAD

**Issue by blackb2b** [gdarko/wp-vimeo-videos#9]
I am using Pro version 1.5.1. I no longer am able to upload the video from front end. It said: 
Sorry, the current remaining quota in the Vimeo account is 0 B and this file is 5.1399 MB. Therefore the video can not be uploaded because the Vimeo account doesn't have enough free space.

But still upload from backend.

**Comment by gdarko** [comment]
Hi @blackb2b ,

I would love to help you. Please email me with admin login details and i will check asap.

info@codeverve.com

Best,
Darko
